services:
    page.menu_builder:
        class: Rad\PageBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    page.main_menu:
            class: Knp\Menu\MenuItem
            factory: ["@page.menu_builder", createMainMenu]
            arguments: ["@request_stack"]
            tags:
                - { name: knp_menu.menu, alias: main }
