services:
    page.menu_builder:
        class: Rad\PageBundle\Menu\MenuBuilder
        arguments: [@knp_menu.factory, @security.token_storage]

    page.main_menu:
            class: Knp\Menu\MenuItem
            factory: ["@page.menu_builder", createMainMenu]
            arguments: ["@request_stack"]
            tags:
                - { name: knp_menu.menu, alias: main }

    form.handler:
        class: Rad\PageBundle\Processor\FormHandler
        arguments: ["@request", @doctrine.orm.entity_manager, @service_container]
        scope: request
        public: true


    listener.entity:
        class: Rad\PageBundle\Listener\EntityListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: preUpdate, connection: default }
            - { name: doctrine.event_listener, event: prePersist, connection: default }