rad_product:
    resource: "@RadProductBundle/Resources/config/routing.yml"
    prefix:   /

rad_magento_config:
    resource: "@RadMagentoConfigBundle/Resources/config/routing.yml"
    prefix:   /

rad_page:
    resource: "@RadPageBundle/Resources/config/routing.yml"
    prefix:   /

rad_user:
    resource: "@RadUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"