services:
    rad.magento.form.product:
        class: Rad\ProductBundle\Form\ProductType
        tags:
            - { name: form.type, alias: rad_productbundle_product }

    rad.product.synchronization:
        class: Rad\ProductBundle\Processor\SynchronizationProcessor
        calls:
            - [ setContainer, [ @service_container ] ]

    rad.product.description:
        class: Rad\ProductBundle\Processor\ProductDescriptionProcessor
        calls:
            - [ setContainer, [ @service_container ] ]

    rad.product.form.handler:
        class: Rad\ProductBundle\Form\Handler
        arguments: ["@request", @doctrine.orm.entity_manager, @service_container]
        scope: request
        public: true