services:
    rad.magento.form.product:
        class: Rad\ProductBundle\Form\ProductType
        tags:
            - { name: form.type, alias: rad_productbundle_product }

    rad.product.synchronization:
        class: Rad\ProductBundle\Processor\SynchronizationProcessor
        calls:
            - [ setContainer, [ @service_container ] ]