rad_magento_admin_color:
    resource: "@RadMagentoConfigBundle/Resources/config/routing/color.yml"
    prefix:   /admin/magento/color

rad_magento_admin_country:
    resource: "@RadMagentoConfigBundle/Resources/config/routing/country.yml"
    prefix:   /admin/magento/country

rad_magento_admin_declinaison:
    resource: "@RadMagentoConfigBundle/Resources/config/routing/declinaison.yml"
    prefix:   /admin/magento/declinaison

rad_magento_admin_support:
    resource: "@RadMagentoConfigBundle/Resources/config/routing/support.yml"
    prefix:   /admin/magento/support

rad_magento_admin_size:
    resource: "@RadMagentoConfigBundle/Resources/config/routing/size.yml"
    prefix:   /admin/magento/size

rad_magento_admin_printing_method:
    resource: "@RadMagentoConfigBundle/Resources/config/routing/printing_method.yml"
    prefix:   /admin/magento/printing-method
