services:
    rad.magento.api:
        class: Rad\MagentoConfigBundle\Processor\ApiProcessor
        arguments:
            - %magento_api_url%
            - %magento_api_user%
            - %magento_api_pass%

    rad.magento.import.category:
        class: Rad\MagentoConfigBundle\Import\Category
        arguments:
            - @rad.magento.api
            - @doctrine


    rad.magento.import.attributeset:
        class: Rad\MagentoConfigBundle\Import\AttributeSet
        arguments:
            - @rad.magento.api
            - @doctrine

    rad.magento.form.size:
        class: Rad\MagentoConfigBundle\Form\SizeType
        tags:
              - { name: form.type, alias: rad_magento_admin_size }
    rad.magento.form.support:
        class: Rad\MagentoConfigBundle\Form\SupportType
        tags:
            - { name: form.type, alias: rad_magento_admin_support }
    rad.magento.form.supportspec:
        class: Rad\MagentoConfigBundle\Form\SupportSpecType
        tags:
            - { name: form.type, alias: rad_magento_admin_supportspec }
    rad.magento.form.declinaison:
        class: Rad\MagentoConfigBundle\Form\DeclinaisonType
        tags:
            - { name: form.type, alias: rad_magento_admin_declinaison }
    rad.magento.form.color:
        class: Rad\MagentoConfigBundle\Form\ColorType
        tags:
            - { name: form.type, alias: rad_magento_admin_color }
    rad.magento.form.colorname:
        class: Rad\MagentoConfigBundle\Form\ColorNameType
        tags:
            - { name: form.type, alias: rad_magento_admin_colorname }
    rad.magento.form.country:
        class: Rad\MagentoConfigBundle\Form\CountryType
        tags:
            - { name: form.type, alias: rad_magento_admin_country }
    rad.magento.form.printingmethod:
        class: Rad\MagentoConfigBundle\Form\PrintingMethodType
        tags:
            - { name: form.type, alias: rad_magento_admin_printingmethod }
    rad.magento.form.description:
        class: Rad\MagentoConfigBundle\Form\DescriptionType
        tags:
            - { name: form.type, alias: rad_magento_admin_description }