services:
    rad.user.form.type:
        class: Rad\UserBundle\Form\UserType
        arguments:
            - %security.role_hierarchy.roles%
            - @service_container
        tags:
            - { name: form.type, alias: rad_userbundle_usertype }